language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kevinhu7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kevinhu7/react-test npm test

after_success:
  - docker build -t kevinhu7/multi-client ./client
  - docker build -t kevinhu7/multi-nginx ./nginx
  - docker build -t kevinhu7/multi-server ./server
  - docker build -t kevinhu7/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push kevinhu7/multi-client
  - docker push kevinhu7/multi-nginx
  - docker push kevinhu7/multi-server
  - docker push kevinhu7/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-628823726612
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY